# Generated by Django 4.2.7 on 2023-11-05 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('narwhal', '0002_rename_imagens_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
