# Generated by Django 4.2.7 on 2023-11-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narwhal', '0005_alter_relatorio_capbarramento_alter_relatorio_ia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='equipamentos',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='requer_sinalizacao',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='riscos_detectados',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
